_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: 3c78321f-e4c7-4d96-8616-e06d506f3543
name: E=MC23
mail: djtechbot@gmail.com
slogan: 'Satellite Of Love'
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
